name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Get latest release
        id: get_release
        uses: actions/github-script@v7
        with:
          script: |
            const response = await github.rest.repos.getLatestRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            return response.data.tag_name.replace(/"/g, '');
      
      - name: Download WASM files
        run: |
          mkdir -p docs
          curl -L "https://github.com/${{ github.repository }}/releases/download/${{ steps.get_release.outputs.result }}/EmojiFarm-wasm.wasm" -o docs/EmojiFarm-wasm.wasm
          curl -L "https://github.com/${{ github.repository }}/releases/download/${{ steps.get_release.outputs.result }}/wasm_exec.js" -o docs/wasm_exec.js
      
      - name: Move and rename HTML file
        run: |
          cp wasm.html docs/index.html
      
      - name: Setup Pages
        uses: actions/configure-pages@v3
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: 'docs'
          
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2 